version: "3.8"

services:
  chirpy-1:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=chirpy1
    env_file:
      - .env
    depends_on:
      migrations:
        condition: service_completed_successfully
    networks:
      - chirpy-network

  chirpy-2:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - DB_NAME=chirpy2
    env_file:
      - .env
    depends_on:
      migrations:
        condition: service_completed_successfully
    networks:
      - chirpy-network

  chirpy-3:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8082:8080"
    environment:
      - DB_NAME=chirpy3
    env_file:
      - .env
    depends_on:
      migrations:
        condition: service_completed_successfully
    networks:
      - chirpy-network

  chirpy-4:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8083:8080"
    environment:
      - DB_NAME=chirpy4
    env_file:
      - .env
    depends_on:
      migrations:
        condition: service_completed_successfully
    networks:
      - chirpy-network

  chirpy-5:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8084:8080"
    environment:
      - DB_NAME=chirpy5
    env_file:
      - .env
    depends_on:
      migrations:
        condition: service_completed_successfully
    networks:
      - chirpy-network

  migrations:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - chirpy-network

  postgres:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env_pg
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chirpy-network

volumes:
  postgres_data:

networks:
  chirpy-network:
    driver: bridge
